pipeline:
  docker:
    #image: plugins/docker
    #secrets: [ docker_username, docker_password ]
    #repo: julianliu/hello-kubernetes
    image: plugins/gcr
    registry: asia.gcr.io
    repo: owlting-gcp/hello-kubernetes
    secrets: [google_credentials]
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
  test:
    image: komljen/drone-kubectl-helm
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    kubectl: "run -n owlting-julian podtest  --rm -i --tty --limits 'memory=64Mi' --image asia.gcr.io/owlting-gcp/hello-kubernetes:${DRONE_COMMIT_SHA} -- pytest"
  predeploy:
    image: busybox:latest
    commands:
      - sed -i "s/hello-kubernetes:latest/hello-kubernetes:${DRONE_COMMIT_SHA}/g" deployment.yaml
    when:
      event: push
      branch:
        - master
  kubectl:
    image: komljen/drone-kubectl-helm
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    kubectl: "apply -n owlting-julian -f deployment.yaml"

