pipeline:
  docker:
    #image: plugins/docker
    #secrets: [ docker_username, docker_password ]
    #repo: julianliu/hello-kubernetes
    image: plugins/gcr
    registry: asia.gcr.io
    repo: owlting-gcp/hello-kubernetes
    secrets: [google_credentials]
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
  #deploy:
  #  image: sh4d1/drone-kubernetes
  #  kubernetes_template: deployment.yaml
  #  kubernetes_namespace: owlting-julian
  #  secrets: [kubernetes_server, kubernetes_cert, kubernetes_token]
  kubectl:
    image: komljen/drone-kubectl-helm
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    kubectl: "apply -f deployment.yaml"
