pipeline:
  pytest:
    image: python:3-alpine
    commands:
      - pip install -r requirements.txt
      - pytest

  docker:
    #image: plugins/docker
    #secrets: [ docker_username, docker_password ]
    #repo: julianliu/hello-kubernetes
    image: plugins/gcr
    registry: asia.gcr.io
    repo: owlting-gcp/hello-kubernetes
    secrets: [google_credentials]
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}

  dockertest:
    image: asia.gcr.io/owlting-gcp/hello-kubernetes:${DRONE_COMMIT_SHA}
    commands:
      - pytest
  
  kubetest:
    image: komljen/drone-kubectl-helm
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    kubectl: "run -n owlting-julian podtest --rm --restart=Never -i --limits memory=128M --image asia.gcr.io/owlting-gcp/hello-kubernetes:${DRONE_COMMIT_SHA} -- rm -rf __pycache__; pytest"

  predeploy:
    image: busybox:latest
    commands:
      - sed -i "s/hello-kubernetes:latest/hello-kubernetes:${DRONE_COMMIT_SHA}/g" deployment.yaml
    when:
      event: push
      branch:
        - master

  kubectl:
    image: komljen/drone-kubectl-helm
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    kubectl: "apply -n owlting-julian -f deployment.yaml"

