pipeline:
  docker:
    #image: plugins/docker
    #secrets: [ docker_username, docker_password ]
    #repo: julianliu/hello-kubernetes
    image: plugins/gcr
    registry: asia.gcr.io
    repo: owlting-gcp/hello-kubernetes
    json_key:
      from_secret: google_credentials
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}

