pipeline:
  docker:
    #image: plugins/docker
    #secrets: [ docker_username, docker_password ]
    #repo: julianliu/hello-kubernetes
    image: plugins/gcr
    registry: asia.gcr.io
    repo: owlting-gcp/hello-kubernetes
    secrets: [google_credentials]
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
  predeploy:
    image: docker:busybox
    commands:
      - sed -i "s/hello-kubernetes:latest/hello-kubernetes:${DRONE_COMMIT_SHA}/g" deployment.yaml
  kubectl:
    image: komljen/drone-kubectl-helm
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    kubectl: "apply -n owlting-julian -f deployment.yaml"

