pipeline:
  docker:
    image: plugins/docker
    privileged: true
    repo: julianliu/hello-kubernetes
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest
