---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: julianliu/hello-kubernetes:latest
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
        ports:
        - name: http-api
          containerPort: 5000
